### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by jerwarren** [valknight/Cohost.py#3]
trying to use the example.py after installing via pip complainst that 'type' object is not subscriptable. Not sure if I'm just holding it wrong or what...

Traceback (most recent call last):
  File "post.py", line 2, in <module>
    from cohost.models.user import User
  File "/home/jer/.local/lib/python3.8/site-packages/cohost/models/user.py", line 3, in <module>
    from cohost.models.project import EditableProject
  File "/home/jer/.local/lib/python3.8/site-packages/cohost/models/project.py", line 90, in <module>
    class EditableProject(Project):
  File "/home/jer/.local/lib/python3.8/site-packages/cohost/models/project.py", line 108, in EditableProject
    def post(self, headline: str, blocks: list[Block], cws: list = [], tags: list = [], adult: bool = False, draft = False):
TypeError: 'type' object is not subscriptable

**Comment by valknight** [comment]
Hi! We use type hinting on a list - which, I don't think is supported in Python3.8 - this works OK on my machine running Python 3.11, and I vaguely remember this working using Python3.9.

Let me know if this works in Python 3.9, and I'll add a note to the README.txt :) 

- val

**Comment by jerwarren** [comment]
Hey, thanks for the pointer. I ended up doing the quick lazy thing and just using 3.11 because it's known-good, but one of these days I'll try 3.9.  I'm not super well versed in python, so I don't know all the hoops to jump through for having multiple versions installed. Someday, though, I'll try it!

Thanks a bunch for this library, though. I'm posting successfully which was my only real objective.

**Comment by valknight** [comment]
godo to hear you're posting successfully ! i'll close this now , as i've made changes that should support 3.8 😄 

to anyone reading this who does have issues on 3.8 in future - please feel free to reopen!
